# Generated by Django 3.2.12 on 2023-02-10 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursematerial',
            old_name='content',
            new_name='file',
        ),
    ]
