# Generated by Django 4.1.5 on 2023-01-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_duration"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="enrolled_courses",
        ),
        migrations.AddField(
            model_name="user",
            name="enrolled_courses",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_students", to="courses.course"
            ),
        ),
    ]
