# Generated by Django 4.1.5 on 2023-01-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_enrolled_courses_user_enrolled_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("MALE", "MALE"), ("FEMALE", "FEMALE"), ("OTHER", "OTHER")],
                default="OTHER",
                max_length=6,
            ),
        ),
    ]
