version: '3.3'

services:

  redis:
    container_name: 'redis'
    image: 'redis:latest'
    ports:
      - '6380:6380'
    networks:
      - edubot
    volumes:
      - 'redisdata:/data'
    restart: unless-stopped

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=edubot
    ports:
      - 5433:5433
    networks:
      - edubot

  edubot_api:
    image: edubot_api
    build:
      context: ./edubot
      dockerfile: Dockerfile
    networks:
      - edubot

    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8005 --timeout 600 --workers 3
    volumes:
      - type: bind
        source: ./edubot
        target: /var/www/media/
    ports:
      - 8005:8005
    depends_on:
      - redis
      - db

volumes:
  redisdata:
  postgres_data:
  media:
  .:


networks:
  edubot:


