# Generated by Django 4.1.5 on 2023-01-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
