# Generated by Django 3.2.12 on 2023-02-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='call_type',
            field=models.CharField(default='WhatsApp', max_length=200),
        ),
    ]
