# Generated by Django 3.2.12 on 2023-01-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_lesson_tutorial_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='lessons',
            new_name='steps',
        ),
    ]
