# Generated by Django 3.2.12 on 2023-01-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_rename_lessons_tutorial_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
