# Generated by Django 3.2.12 on 2023-01-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20230128_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='instructions',
            field=models.TextField(default='Instruction'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
