# Generated by Django 3.2.12 on 2023-01-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_alter_lesson_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('document', 'Document'), ('quiz', 'Quiz'), ('audio', 'Audio'), ('image', 'Image')], default='text', max_length=200),
        ),
    ]
