# Generated by Django 3.2.12 on 2023-01-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_callrequest_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrequest',
            name='duration',
        ),
    ]
