# Generated by Django 4.1.5 on 2023-01-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="access_permissions",
            field=models.CharField(
                choices=[
                    ("1", "Curated Content"),
                    ("2", "Curated Content + Whatsapp Calls"),
                    ("3", "Curated Content + Whatsapp Calls + Zoom Calls"),
                ],
                default="1",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="duration",
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="package",
            name="name",
            field=models.CharField(
                choices=[("bronze", "BRONZE"), ("silver", "SILVER"), ("gold", "GOLD")],
                default="bronze",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
