# Generated by Django 3.2.12 on 2023-01-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_remove_package_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='access_permissions',
            field=models.CharField(choices=[('1', 'Curated Content'), ('2', 'Curated Content + Whatsapp Calls'), ('3', 'Curated Content + Whatsapp Calls + Zoom Calls'), ('4', 'Curated Content + Whatsapp Calls + Zoom Calls + Live Classes')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(choices=[('bronze', 'BRONZE'), ('silver', 'SILVER'), ('gold', 'GOLD'), ('platinum', 'PLATINUM')], default='bronze', max_length=255, unique=True),
        ),
    ]
