# Generated by Django 3.2.12 on 2023-02-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20230128_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.CharField(choices=[('1', 'Course Registration'), ('2', 'Assignment Outsourcing')], default='1', max_length=255),
        ),
    ]
