# Generated by Django 3.2.12 on 2023-02-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_package_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(choices=[('bronze', 'BRONZE'), ('silver', 'SILVER'), ('gold', 'GOLD'), ('platinum', 'PLATINUM')], default='bronze', max_length=255),
        ),
    ]
