# Generated by Django 3.2.12 on 2023-02-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_alter_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='service_type',
            field=models.CharField(choices=[('course_registration', 'Course Registration'), ('assignment_outsourcing', 'Assignment Outsourcing')], default='course_registration', max_length=255),
        ),
    ]
