# Generated by Django 4.1.5 on 2023-01-15 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assignments", "0002_pendingwork_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingwork",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_works",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
