# Generated by Django 4.1.5 on 2023-01-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_alter_pendingwork_uploaded_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingwork",
            name="submitted_assignments",
            field=models.ManyToManyField(
                blank=True, related_name="pending_works", to="assignments.assignment"
            ),
        ),
    ]
