# Generated by Django 4.1.5 on 2023-01-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_alter_pendingwork_submitted_assignments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[("Outsourced", "Outsourced"), ("In-House", "In-House")],
                default="In-House",
                max_length=255,
            ),
        ),
    ]
