# Generated by Django 3.2.12 on 2023-02-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_assignment_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='field_of_study',
            field=models.CharField(default='Other', max_length=255),
        ),
    ]
