# Generated by Django 4.1.5 on 2023-01-08 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("BRONZE", "BRONZE"),
                            ("SILVER", "SILVER"),
                            ("GOLD", "GOLD"),
                        ],
                        default="BRONZE",
                        max_length=255,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_permissions",
                    models.CharField(
                        choices=[
                            ("1", "Curated Content"),
                            ("2", "Curated Content + Whatsapp Calls"),
                            ("3", "Curated Content + Whatsapp Calls + Zoom Calls"),
                        ],
                        default="1",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "SubscriptionPackage",
                "verbose_name_plural": "SubscriptionPackages",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
    ]
