# Generated by Django 4.1.5 on 2023-01-11 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubscriptionPackage",
        ),
    ]
