# Generated by Django 3.2.12 on 2023-02-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_alter_package_service_type'),
        ('subscriptions', '0003_delete_subscriptionpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='packages.package'),
        ),
    ]
