# Generated by Django 4.1.5 on 2023-01-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[("1", "Pending"), ("2", "Paid")], default="1", max_length=255
            ),
        ),
    ]
