# Generated by Django 4.1.5 on 2023-01-13 11:43

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="reference",
            field=models.CharField(
                default=payments.models.get_payment_reference, max_length=255
            ),
        ),
    ]
