# Generated by Django 4.1.5 on 2023-01-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_payment_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
