# Generated by Django 4.1.5 on 2023-01-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_payment_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(default="paypal", max_length=255),
        ),
    ]
