# Generated by Django 4.1.5 on 2023-01-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("1", "Pending"),
                    ("2", "Paid"),
                    ("3", "Failed"),
                    ("4", "Cancelled"),
                    ("5", "Declined"),
                ],
                default="1",
                max_length=255,
            ),
        ),
    ]
