# Generated by Django 4.1.5 on 2023-01-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_alter_payment_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Awaiting Delivery", "Awaiting Delivery"),
                    ("Paid", "Paid"),
                    ("Failed", "Failed"),
                    ("Cancelled", "Cancelled"),
                    ("Declined", "Declined"),
                ],
                default="Failed",
                max_length=255,
            ),
        ),
    ]
