# Generated by Django 3.2.12 on 2023-02-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_payment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='upstream_reference',
            field=models.CharField(default='', max_length=255),
        ),
    ]
