# Generated by Django 3.2.12 on 2023-02-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_payment_upstream_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Created', 'Created'), ('Awaiting Delivery', 'Awaiting Delivery'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Declined', 'Declined')], default='Failed', max_length=255),
        ),
    ]
